<?xml version="1.0" encoding="utf-8"?><Database Name="BazaZwierzat" Class="PolaczenieBazaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;C:\Users\idea 305\Documents\BazaZwierzat.mdf&quot;;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ADZZ.Properties.Settings" SettingsPropertyName="BazaZwierzatConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Historia_cen" Member="Historia_cen">
    <Type Name="Historia_cen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cena" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="okres_od" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="okres_do" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_kategoria_rozliczen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Kategoria_rozliczen_Historia_cen" Member="Kategoria_rozliczen" ThisKey="id_kategoria_rozliczen" OtherKey="Id" Type="Kategoria_rozliczen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Historia_Stada" Member="Historia_Stada">
    <Type Name="Historia_Stada">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="okres_od" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="okres_do" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ilosc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Historia_Stada_Stado" Member="Stado" ThisKey="Id" OtherKey="id_historia" Type="Stado" />
    </Type>
  </Table>
  <Table Name="dbo.Kategoria_rozliczen" Member="Kategoria_rozliczen">
    <Type Name="Kategoria_rozliczen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="czyPrzychod" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Kategoria_rozliczen_Historia_cen" Member="Historia_cen" ThisKey="Id" OtherKey="id_kategoria_rozliczen" Type="Historia_cen" />
      <Association Name="Kategoria_rozliczen_Rozliczenia" Member="Rozliczenia" ThisKey="Id" OtherKey="id_kategoria" Type="Rozliczenia" />
    </Type>
  </Table>
  <Table Name="dbo.Rasa" Member="Rasa">
    <Type Name="Rasa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="id_gatunek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rasa_Zwierze" Member="Zwierze" ThisKey="Id" OtherKey="id_rasa" Type="Zwierze" />
      <Association Name="Gatunek_Rasa" Member="Gatunek" ThisKey="id_gatunek" OtherKey="Id" Type="Gatunek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stado" Member="Stado">
    <Type Name="Stado">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nr_stada" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_gatunek" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_historia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Stado_Rozliczenia" Member="Rozliczenia" ThisKey="Id" OtherKey="id_stado" Type="Rozliczenia" />
      <Association Name="Historia_Stada_Stado" Member="Historia_Stada" ThisKey="id_historia" OtherKey="Id" Type="Historia_Stada" IsForeignKey="true" />
      <Association Name="Gatunek_Stado" Member="Gatunek" ThisKey="id_gatunek" OtherKey="Id" Type="Gatunek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zwierze" Member="Zwierze">
    <Type Name="Zwierze">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_urodzenia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nr_kolczyka" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="plec" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="okres_od" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="okres_do" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_rasa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Zwierze_Rozrod" Member="Rozrod" ThisKey="Id" OtherKey="id_zwierze" Type="Rozrod" />
      <Association Name="Zwierze_Rozliczenia" Member="Rozliczenia" ThisKey="Id" OtherKey="id_zwierze" Type="Rozliczenia" />
      <Association Name="Rasa_Zwierze" Member="Rasa" ThisKey="id_rasa" OtherKey="Id" Type="Rasa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rozrod" Member="Rozrod">
    <Type Name="Rozrod">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="czyRuja" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="id_zwierze" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Zwierze_Rozrod" Member="Zwierze" ThisKey="id_zwierze" OtherKey="Id" Type="Zwierze" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rozliczenia" Member="Rozliczenia">
    <Type Name="Rozliczenia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="opis" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ilosc_litrow" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_zwierze" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_kategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_stado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kwota" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Kategoria_rozliczen_Rozliczenia" Member="Kategoria_rozliczen" ThisKey="id_kategoria" OtherKey="Id" Type="Kategoria_rozliczen" IsForeignKey="true" />
      <Association Name="Stado_Rozliczenia" Member="Stado" ThisKey="id_stado" OtherKey="Id" Type="Stado" IsForeignKey="true" />
      <Association Name="Zwierze_Rozliczenia" Member="Zwierze" ThisKey="id_zwierze" OtherKey="Id" Type="Zwierze" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gatunek" Member="Gatunek">
    <Type Name="Gatunek">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="czyStado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Gatunek_Rasa" Member="Rasa" ThisKey="Id" OtherKey="id_gatunek" Type="Rasa" />
      <Association Name="Gatunek_Stado" Member="Stado" ThisKey="Id" OtherKey="id_gatunek" Type="Stado" />
    </Type>
  </Table>
</Database>